### ISSUE TITLE
Alarm/timer sensors should be binary_sensor

### ISSUE THREAD

**Issue by gary-reyes** [leikoilja/ha-google-home#106]
The alarm/timer sensor provide a binary value (are there any active alarms/timer). It is odd that this information is not provided through a binary_sensor instead

**Comment by leikoilja** [comment]
Is [this](https://developers.home-assistant.io/docs/core/entity/binary-sensor/) what you refer to, @gary-reyes? If so, help me see why would that be better to have them as binary? :)

**Comment by gary-reyes** [comment]
Yes.
The alarm/timer sensors are providing an off/on value indicating that an alarm is available. This is exactly what binary sensors are intended for.   The link you provided even provides this information.
is_on | boolean | Required | If the binary sensor is currently on or off.
-- | -- | -- | --

A sensor can provide a text state or a numerical state as seen in https://developers.home-assistant.io/docs/core/entity/sensor

It just seems seems weird that a sensor value is providing binary values. I have not seen this in other components. Is there a reason for not using a binary sensor?

**Comment by DurgNomis-drol** [comment]
This is because in the development we changed somethings around and ended up with that it just shows state `on` or `off`. Before that it showed the next alarm. I think there are exceptions to the rule of using `binary_sensor` and this does live in that gray area. But it is something to have in mind. The state should probably be `set` `none set` instead if we change anything.

**Comment by leikoilja** [comment]
Thanks for laying it out, @gary-reyes. 
I can see how it could be a binary sensor, however, it doesn't seem to make sense to have it as a binary sensor when there is a massive pile of information in the sensor's attributes. Perhaps we should make the state of the sensor "set"/"not set" as @DurgNomis-drol is proposing or even just an integer number how many alarms/timers there is in the device? 

@KapJI, what do you think?

**Comment by gary-reyes** [comment]
Either would work as solutions.

**Comment by leikoilja** [comment]
@DurgNomis-drol would you have time and interest to take a look at fixing this one as well? :) 
I m afraid i won't have time to look at this until tomorrow night, maybe Thursday :)

**Comment by DurgNomis-drol** [comment]
Yes no problem, waiting for @KapJI opinion and then i will look into to it 😄

**Comment by KapJI** [comment]
After looking at documentation about `sensor` and `binary_sensor` it seems to me that the best way is to keep it `sensor` with device class `timestamp` and set the value to the next alarm/timer (in ISO8601 format) or `off`.

**Comment by DurgNomis-drol** [comment]
@KapJI But this defeats the purpose of the `next_alarm` and `next_timer` sensor we have?

**Comment by KapJI** [comment]
So probably we can merge them? 🙂

**Comment by DurgNomis-drol** [comment]
I think it is better to have them separated as we have now and then change the state for `on` or `off` to `set` or `none set`. Especially if we introduce other things as attributes to either sensor.

Either way I need to sleep on it 😄 

But if the majority whats them merged i am okay with that 😄

**Comment by KapJI** [comment]
How is this implemented for android alarms?

**Comment by DurgNomis-drol** [comment]
[Here](https://companion.home-assistant.io/docs/core/sensors/#next-alarm-sensor) is a link to `mobile_app` implementation:

**Comment by leikoilja** [comment]
If we talk about personal preferences I would suggest we keep the next alarm/timer as is to mimic the mobile phone sensor, but replace the state of `alarms`/`timers` sensor to just say the number of alarms/timers set. 
I have implemented something similar in Habitica integration (that is core HA) and it got merged with the state just being a number of elements in the sensor. :)

**Comment by dennyreiter** [comment]
> If we talk about personal preferences I would suggest we keep the next alarm/timer as is to mimic the mobile phone sensor, but replace the state of `alarms`/`timers` sensor to just say the number of alarms/timers set.
> I have implemented something similar in Habitica integration (that is core HA) and it got merged with the state just being a number of elements in the sensor. :)

This seems to make the most sense, having the state be the number of timers.

**Comment by leikoilja** [comment]
Okay, let's make it that way then 💥  @DurgNomis-drol still up for a fun challenge? :) Leme know if you are not available, i ll find some time for that

**Comment by DurgNomis-drol** [comment]
I will look into it today. 😄 Should be a trivial change to make.

**Comment by KapJI** [comment]
It's still not clear to me what's the advantage of having 2 sensors for alarms. IMO the simpler the better. Basically it can follow next alarm from `mobile_app` with information about other alarms in attributes. This way you should have twice less sensors 🙂
And if someone needs number of alarms it can be get with `length` jinja2 template filter.

**Comment by DurgNomis-drol** [comment]
After thinking more about it. This could also be said about the device sensor we create. As there is no real use for it. That should also be removed then.

I think that having two separate sensors will make it more clear to the user what there purpose is.

I would normally agree with you about simplicity, but i am leaning more and more towards not changing anything. I don't think it is worth making a breaking change over this, arguably, small thing. We are not aiming to get it include in core anyway. We can always change it later on if its really needed.

**Comment by KapJI** [comment]
Device sensor with auth token is useful if someone wants to use different api of google home. We should keep it.

I agree about the breaking change. Although changing the state format is also a breaking change, but not as significant probably.

My point is these sensors ultimately represent the same data and having them merged doesn't make UX any worse because the next alarm is still in the state value and you can access it the same way as before.

**Comment by DurgNomis-drol** [comment]
I don't personally use the auth token sensor. But it is a advanced feature. There are not that many useful API endpoints anyway and most of them are about setting it up. But i don't care if we have it or not. 😄 

You have some valid points about it being better to do it now and that they present the same data, but they do it in a different way. 

I am gonna go with decision that the majority wants 😄 But i am gonna tag out of implementing a fix. I think it would be best that the implementation that we go with, is implemented by the person who suggest it.

**Comment by KapJI** [comment]
I'm ok with implementing it 🙂

**Comment by leikoilja** [comment]
@KapJI mind taking the lead on that? 💯  😄

**Comment by KapJI** [comment]
Yep, sure! Will do in the next couple of days.

**Comment by leikoilja** [comment]
Perfect, thanks, @KapJI
