### ISSUE TITLE
Getting a Config Flow Could Not Be Loaded

### ISSUE THREAD

**Issue by soloam** [leikoilja/ha-google-home#183]
## Describe the bug

I try to install and I get this error:
![image](https://user-images.githubusercontent.com/11949987/114430013-dfbca480-9bb5-11eb-8ecb-1cd3e9d29c6e.png)

I tried to see the log, but no information and apparently the integration is installed

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
1.4.1

Home Assistat  2021.4.3 in FreeNas Jail
```

## Logs

strange but I don't have any log output during the install

```text

```

**Comment by KapJI** [comment]
Please enable debug logs and attach the whole `home-assistant.log` after home assistant restart.

**Comment by soloam** [comment]
I'll be back to this on the weekend! Thank you

**Comment by SuperSuave** [comment]
[home-assistant.log](https://github.com/leikoilja/ha-google-home/files/6388197/home-assistant.log)

Hi! I'm having the same issue, I've hopefully attached what you're looking for. If not, please let me know!
Install Info:
HAss:
- Version: core-2021.4.6
- Installation Type: Home Assistant Container
HACS: 1.12.1

I've tried installing all versions of the HA Google Home integration

**Comment by leikoilja** [comment]
@SuperSuave, it's a rather big log file. What are we looking at again? 😄 Can you refer to a line number or a timestamp around the error please

**Comment by KapJI** [comment]
@SuperSuave I think this is the reason:
```
2021-04-27 23:35:09 ERROR (SyncWorker_10) [homeassistant.util.package] Unable to install package glocaltokens==0.3.1: ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vnzfbo2a/grpcio-tools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vnzfbo2a/grpcio-tools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1y4q3hr3
         cwd: /tmp/pip-install-vnzfbo2a/grpcio-tools/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vnzfbo2a/grpcio-tools/setup.py", line 112, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-install-vnzfbo2a/grpcio-tools/setup.py", line 73, in check_linker_need_libatomic
        cc_test = subprocess.Popen(['cc', '-x', 'c++', '-std=c++11', '-'],
      File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cc'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

You need to have compiler installed (`build-essential` on debian based systems).

**Comment by SuperSuave** [comment]
@leikoilja Apologies, I honestly didn't know what to even look for...

It looks like @KapJI found it. I'm running this on OpenMediaVault 5 under Docker. 
I tried installing build-essential, and got back:

> "build-essential is already the newest version (12.6). 0 upgraded, 0 newly installed, 0 to remove and 31 not upgraded."

Does this need to be done on the container? I don't know how to do that.

**Comment by KapJI** [comment]
Yes, it should be inside container where HA runs.

**Comment by SuperSuave** [comment]
> Yes, it should be inside container where HA runs.

I'm unsure of how to do that. Can you point me in the direction of some directions for this? 
I'm not quite sure what to Google for on that.

**Comment by KapJI** [comment]
https://www.tutorialspoint.com/installing-linux-packages-inside-a-docker-container

**Comment by SuperSuave** [comment]
I didn't have any luck following that guide you posted. I guess Home Assistant Docker is based on Alpine and uses different things?
After a lot of searching around, I wound up finding another [related issue that helped here](https://github.com/leikoilja/ha-google-home/issues/14). From what I can tell on that issue, this should've been resolved?

This got me up and running:

- sudo docker exec -it (container ID) bash
- apk add gcc g++ linux-headers

**Comment by leikoilja** [comment]
Oh, awesome work, @KapJI for digging it out. The moment i saw how long the log file was i "gave up" without even trying 😅 🤦 
Awesome, happy to hear that you managed to fix dependencies, @SuperSuave. Yes indeed, the issue with `grpcio` dependencies should have been fixed a few month ago on the latest HA builds. Are you running the latest HA container?

**Comment by SuperSuave** [comment]
@leikoilja  Sorry, I didn't see you had asked me a question. I just came back here because I'm still having the issue after upgrading.

I was running the latest then(2021.4.6), and just upgraded to 2021.5.1

Running on OMV5, using Portainer 2.1.1

This is from the info section on my HA install.
<html>
<body>


Version | core-2021.5.1
-- | --
Installation Type | Home Assistant Container
Development | false
Supervisor | false
Docker | true
Virtual Environment | false
Python Version | 3.8.9
Operating System Family | Linux
Operating System Version | 5.10.0-0.bpo.5-amd64
CPU Architecture | x86_64


</body>
</html>

**Comment by leikoilja** [comment]
@SuperSuave i am going to close this issue since the original dependency problem seems to be fixed for you. Feel free to open a new ticket if you have other issues arising :)
