### ISSUE TITLE
2022.03.0b0 fails to load

### ISSUE THREAD

**Issue by brianhanifin** [leikoilja/ha-google-home#470]
## Describe the bug

After installing Home Assistant 2022.03.0b0 this integration fails to load with the following error  

```text
Logger: homeassistant.setup
Source: setup.py:155 
First occurred: 4:47:43 PM (1 occurrences) 
Last logged: 4:47:43 PM

Setup failed for google_home: Requirements for google_home not found: ['glocaltokens==0.6.2'].
```

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
1.9.7
```

## Logs

```text
Add your logs here.
```

**Comment by pschneider87** [comment]
yes, same here with latest beta release

**Comment by ArnyminerZ** [comment]
Try to install `glocaltokens` manually with
```
pip3 install glocaltokens
```
And paste the command feedback.

**Comment by leikoilja** [comment]
Seems to be caused by Python pips newer resolver, see https://github.com/leikoilja/glocaltokens/issues/218 for more info.

**Comment by leikoilja** [comment]
Fixed and released in [v1.9.8](https://github.com/leikoilja/ha-google-home/releases/tag/v1.9.8) 💥

**Comment by pschneider87** [comment]
I can't install. Hacs times out when installing latest version

**Comment by leikoilja** [comment]
hmmm, sound a bit more like HACS issue? Does it still happen, @pschneider87 ?

**Comment by pschneider87** [comment]
![Screenshot_20220226-155525~2.png](https://user-images.githubusercontent.com/17707309/155847674-d9a19f9a-a824-4f5f-a303-93d171e2276f.png)

Yes, I still get the error when try to update

**Comment by leikoilja** [comment]
@pschneider87, from the error extract you have sent above it, seems that HA is timeouting while installing the integration. Can you please first check your network connection on your HA (as the log suggests)? Secondly, make sure you are on the latest versions of HACS / Home Assistant OS / Home Assistant. Thirdly, make sure you remove the old integration (just to avoid any conflicts. And at last, if none of the previous steps have helped, please open a new issue filling up all required information as well as logs extracts, so we could have more information how to help you :)

**Comment by pschneider87** [comment]
seems to be an HACS issue, can't reinstall, and other integrations are failing to update as well.
